name: Deploy Star Wars API to AWS

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

defaults:
  run:
    working-directory: backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Serverless
        run: npm install -g serverless

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID_SW: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_SW: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless deploy
