service: starwars-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1

  deploymentBucket:
    name: ${env:AWS_S3_BUCKET}

functions:
  starwarsfact:
    handler: handler.starwarsfact
    events:
      - http:
          path: starwarsfact
          method: get
          cors: true
