name: Deploy Star Wars API to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.14.0'

    - name: Install Dependencies
      run: npm install
      working-directory: backend/starwars-api

    - name: Install Serverless
      run: npm install -g serverless
      working-directory: ./AWS-Cloud-Challenge/backend/starwars-api

    - name: Deploy with Serverless
      run: serverless deploy
      env:
        AWS_ACCESS_KEY_ID_SW: ${{ secrets.AWS_ACCESS_KEY_ID_SW }}
        AWS_SECRET_ACCESS_KEY_SW: ${{ secrets.AWS_SECRET_ACCESS_KEY_SW }}
