name: "Upload website to S3"

on:
  push:
    branches:
      - main

permissions:
  contents: read  # Grants read-only access to repo contents
  id-token: write  # Required for OpenID Connect (OIDC) authentication

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Use a pinned version of checkout
      - uses: jakejarvis/s3-sync-action@be0c4ab89158cac4278689ebedd8407dd5f35a83
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'assets'
